Feature/buttons
GlebKirsan/liza-alert-test-platform pull request #10
Opened 2022-05-21 18:09 UTC by pblHbKa

На панели добавила все варианты кнопок, забирайте каждый свои

2022-05-22 05:05 UTC, Virshinia requested changes
Добавила предложения по изменениям. Некоторые могут показаться дискусионными, если так. то предалагаю обсудить в слаке если что)

2022-05-22 05:05 UTC, Virshinia commented on index.html
> +    <nav class="action-panel">
Судя по всему, лучше тут не использовать nav тег, а взять просто div
"Notice that NOT all links of a document should be inside a <nav> element. The <nav> element is intended only for major block of navigation links."
https://www.w3schools.com/tags/tag_nav.asp

2022-05-22 06:36 UTC, pblHbKa commented on index.html
> +        <div class="button__img button__img_elem_arrow-back-active"></div>
Это не контекстное изображение, оно не несет в себе отдельной смысловой нагрузки, рядов с картинкой есть текст, который и есть ее смысл. Вот можно, наверное текст через p сделать, семантически правильнее будет и этот текст и озвучится

2022-05-22 06:37 UTC, pblHbKa commented on index.html
> +        <div>Назад</div>
Блок отдельный нужен, потому что тебе нужно расположить 2 элемента рядом, но с определенным отступом. Единственное, как выше писала, div на p заменить

2022-05-22 06:39 UTC, IliaGorin commented on blocks/button/_disabled/button_disabled.css
> +    color: #9397a3;
Я на неактивной кнопке делал cursor: not-allowed; тогда точно понятно :)

2022-05-22 06:40 UTC, pblHbKa commented on blocks/button/button.css
> +.button {
Другие модификаторы все равно будут определять те свойства что у них есть сейчас, ведь если ты уберешь цвет из button, то его все равно где оранжевой кнопки нужно задать. То есть модификаторы существующие как раз не поменяются. Вопрос только в "основной" кнопке.
Если убрать из button стили оформления, то нужен доп. модификатор. То есть еще больше элементов. А так, если ты указала стиль button, то кнопка уже оформлена по умолчанию, больше ничего делать не нужно

2022-05-22 06:44 UTC, pblHbKa commented on index.html
> +    <nav class="action-panel">
Принято

2022-05-22 06:44 UTC, pblHbKa commented on blocks/button/_disabled/button_disabled.css
> +    color: #9397a3;
Принято

2022-05-22 06:45 UTC, pblHbKa commented on blocks/button/button.css
> +	width: 184px;
Принято. Но и к совсем большому контенту нужно как-то подготовиться. Сделаю

2022-05-22 14:41 UTC, pblHbKa commented on blocks/button/_disabled/button_disabled.css
> +    color: #9397a3;
курсор, который по not-allowed, я что-то не помню на сайтах живых особо, хотя да, понятней некуда. Посмотрела примеры, или текстовый или по умолчанию обычно. Сделала cursor: default;

2022-05-22 16:38 UTC, GlebKirsan requested changes

2022-05-22 16:38 UTC, GlebKirsan commented on blocks/button/__img/button__img.css
> +    width: 16px;
Эти размеры не всегда подходят
<img width="408" alt="Screenshot 2022-05-22 at 19 29 41" src="https://user-images.githubusercontent.com/32064992/169705750-d97f0c98-df6b-4e02-a8e8-617d6b632381.png">

2022-05-22 16:38 UTC, GlebKirsan commented on index.html
> +      <button type="button" class="button button_navigation">
`navigation` не выглядит, как булевый модификатор, надо бы переименовать

2022-05-22 17:05 UTC, GlebKirsan requested changes

2022-05-22 17:05 UTC, GlebKirsan commented on index.html
> +        <svg class="button__img_type_navigation button__img_position_left">
А теперь один модификатор без класса самого элемента 🙂

2022-05-22 18:18 UTC, GlebKirsan approved these changes

2022-05-22 20:54 UTC, Miteugene approved these changes

2022-05-23 07:22 UTC, Virshinia approved these changes

2022-05-23 07:22 UTC, merged