add title for collapsing list
GlebKirsan/liza-alert-test-platform pull request #12
Opened 2022-05-21 20:01 UTC by Miteugene

2022-05-21 20:34 UTC, pblHbKa approved these changes

2022-05-22 04:17 UTC, Virshinia commented on index.html
> +      <h1 class="title">Содержание</h1>
Давай лучше h2.
Все-таки h1 должен быть в основном контенте и нести семантическое значение для каждой страницы.

2022-05-22 04:18 UTC, Virshinia requested changes
Лучше заменить h1 на h2

2022-05-22 09:35 UTC, Miteugene commented on index.html
> +      <h1 class="title">Содержание</h1>
Да, верно. А я просто скопировал его с соседнего блока, не знаю кто его делал.
У себя сейчас поправлю

2022-05-22 21:04 UTC, Virshinia approved these changes

2022-05-22 21:04 UTC, merged