Bugfix/bem names test pages
GlebKirsan/liza-alert-test-platform pull request #47
Opened 2022-05-29 11:20 UTC by IliaGorin

Исправлены наименования классов согласно БЭМ для страниц с тестами (test__result_big-text, test__result-paragraph). 
Класс button-submit_enabled переделан с булевого на ключ значение (Status_enabled status_disabled).
Исправлены ссылки.
Правки для прохождения HTML валидатора.

2022-05-29 17:12 UTC, Virshinia commented on about-test.html
> -      <div class="button__img button__img_type_forward button__img_disabled"></div>
Это моя страница) Возможно тут будет конфликт )

2022-05-29 17:55 UTC, GlebKirsan requested changes

2022-05-29 17:55 UTC, GlebKirsan commented on blocks/test/__button-redo/test__button-redo.css
> +  width: 176px;
Нужна жёсткая ширина?

2022-05-29 17:55 UTC, GlebKirsan commented on blocks/test/__button-submit/_status/test__button-submit_status_disabled.css
> +.test__button-submit_status_disabled {
Почему снова разделили булевый модификатор на сложный?

2022-05-29 17:55 UTC, GlebKirsan commented on blocks/test/__result-paragraph/_separate-line/test__result-paragraph_separate-line.css
> +.test__result-paragraph_separate-line {
Модификатор не по БЭМ

2022-05-29 18:32 UTC, IliaGorin commented on blocks/test/__button-redo/test__button-redo.css
> +  width: 176px;
боюсь что в данном случае да, кнопки вперед назад у нас во флекс контейнере, потому держат размер согласно указанного минимального, а кнопка пересдать у меня просто блок в потоке, без указания жесткой ширины она растягивается на всю ширину родителя. Лепить лишний контейнер смысла тоже не вижу, хотя можно section 'test' сделать грид контейнером, тогда ссылка не растягивается и без фиксации ширины.

2022-05-29 18:35 UTC, IliaGorin commented on blocks/test/__button-submit/_status/test__button-submit_status_disabled.css
> +.test__button-submit_status_disabled {
Потому что ревью написали, только я вот ревью что-то теперь найти не могу(

2022-05-29 18:39 UTC, IliaGorin commented on blocks/test/__result-paragraph/_separate-line/test__result-paragraph_separate-line.css
> +.test__result-paragraph_separate-line {
вот хз, у нас есть обычный параграф, который мы используем по умолчанию. Внутри него, на одной строке нужно сделать перенос, в первом варианте я вставлял <br>, ревью не ругался, но по идее по правилам его нельзя использовать. Делать тут ключ_значение совсем странно. Идея была сделать булевый, типа нормальный параграф по умолчанию, separate-line - если надо отделить строку внутри. Нужно мнение аудитории :)

2022-05-29 21:05 UTC, GlebKirsan commented on page-test.html
> +          <button class="test__button-submit test__button-submit_status_disabled button__title" type="submit" disabled>
Ещё вот тут `button__title` — элемент блока `button`, но вне блока

2022-05-29 21:08 UTC, GlebKirsan commented on blocks/test/__button-submit/_status/test__button-submit_status_disabled.css
> +.test__button-submit_status_disabled {
Без ревью не понятно 🙂 
[Вот тут ](https://github.com/l1v9l9s7l/liza-alert-cynological-direction/pull/20) ревьюер пишет, что в похожей ситуации (кмк, похожая) стоит использовать булевый
![image](https://user-images.githubusercontent.com/32064992/170891484-6cf70447-8e59-4010-913b-7073d4dbfc17.png)

2022-05-30 06:06 UTC, IliaGorin commented on blocks/test/__result-paragraph/_separate-line/test__result-paragraph_separate-line.css
> +.test__result-paragraph_separate-line {
Может его вообще вынести в отдельный блок и сделать микс?

2022-05-30 17:54 UTC, closed without merging