add breadcrumbs
GlebKirsan/liza-alert-test-platform pull request #5
Opened 2022-05-20 16:45 UTC by Miteugene

2022-05-20 17:00 UTC, Virshinia commented on blocks/breadcrumbs/__list/breadcrumbs__list.css
> +  grid-auto-columns: repeat(auto-fit, 1fr) minmax(min-content, max-content);
А что у тебя эта строчка делает? Просто у меня на неё ругается ide и по идее и без неё все работает

2022-05-20 17:03 UTC, Virshinia requested changes
Все ок, кроме одного момента в комментариях

2022-05-20 19:38 UTC, Miteugene commented on blocks/breadcrumbs/__list/breadcrumbs__list.css
> +  grid-auto-columns: repeat(auto-fit, 1fr) minmax(min-content, max-content);
Спасибо, исправил. 
Опечатался, там должен был быть grid-template-columns, хотел задать логику колонок, но действительно даже без него работает, так как overflow: hidden; для элементов списка делают свою работу.

2022-05-21 08:11 UTC, IliaGorin commented on blocks/breadcrumbs/__item/breadcrumbs__item.css
> +  line-height: 24px;
если мы в основном блоке приняли интерлиньяж делать коэф, может тут тоже? чтобы однообразие было 
".course-content__info-text {
    font-size: 18px;
    line-height: 1.2;"

2022-05-21 14:53 UTC, IliaGorin commented on blocks/breadcrumbs/__item/breadcrumbs__item.css
> +  line-height: 24px;
правда момент еще в том, что и в макете, и готовых страницах используют line-height: 1.33; надо наверное тогда везде исправить будет

2022-05-21 15:24 UTC, IliaGorin approved these changes

2022-05-21 18:26 UTC, merged