Bugfix/bem names test pages 2
GlebKirsan/liza-alert-test-platform pull request #50
Opened 2022-05-30 17:52 UTC by IliaGorin

Правки по БЭМ наименованиям

2022-05-30 20:29 UTC, pblHbKa requested changes

2022-05-30 20:29 UTC, pblHbKa commented on blocks/test/__button-submit/test__button-submit.css
> +  max-width: 200px;
Остался и width и max-width. При этом максимальная ширина меньше обычной и меньше макета

2022-05-30 20:29 UTC, pblHbKa commented on page-test-result-positive.html
> +            Нажите &laquo;Далее&raquo; чтобы продолжить.<br>
white-space: pre; поможет избавиться от br.

2022-05-31 01:25 UTC, GlebKirsan requested changes

2022-05-31 01:25 UTC, GlebKirsan commented on blocks/test/__result-paragraph/_big-text/test__result-paragraph_big-text.css
> +.test__result-paragraph_big-text {
Название модификатора не по БЭМ :) Написан, как булевый, а на самом деле ключ-значение

2022-05-31 04:12 UTC, IliaGorin commented on blocks/test/__button-submit/test__button-submit.css
> +  max-width: 200px;
Копипаст зло)) я просто скопировал button title, потому такая мешанина

2022-05-31 04:13 UTC, IliaGorin commented on page-test-result-positive.html
> +            Нажите &laquo;Далее&raquo; чтобы продолжить.<br>
Я все равно не понимаю эту войну с br. Если надо будет заменять текст, так все равно менять весь кусок, в чем будет разница что внутри этого куска, если мы его удалили)

2022-05-31 04:14 UTC, IliaGorin commented on blocks/test/__result-paragraph/_big-text/test__result-paragraph_big-text.css
> +.test__result-paragraph_big-text {
Тогда надо делать и обычный шрифт как модификатор наверное

2022-05-31 05:14 UTC, pblHbKa commented on page-test-result-positive.html
> +            Нажите &laquo;Далее&raquo; чтобы продолжить.<br>
Разница будет в том, что при br человеку, который будет добавлять/менять текст, надо мало того что знать про этот тег, так еще и не забыть поставить где нужно.
А если ты пишешь через white-space: pre, то ты даешь инструкцию: отображать текст на странице точно так. как он написан. И менять текст может любой не обученный верстке человек

2022-05-31 05:48 UTC, IliaGorin commented on page-test-result-positive.html
> +            Нажите &laquo;Далее&raquo; чтобы продолжить.<br>
Мне кажется лучше не допускать к редактированию человека, который не разбирается в верстке) но вообще да, заданный заранее стиль скорее всего сработает, по логике как вставляем текст, так он и будет отображаться

2022-05-31 18:17 UTC, closed without merging