feat:добавить общие блок - заголовок, ссылка, текст в контенте
GlebKirsan/liza-alert-test-platform pull request #6
Opened 2022-05-20 20:53 UTC by Virshinia

2022-05-20 22:23 UTC, Miteugene commented on blocks/link/link.css
> +    transition: .5s ease-out;
@Virshinia, ты наверно заметила, что у тебя анимация ссылки какая-то дерганная в конце? Смотри, как я попробовал сделать, так вроде плавно работает:

.link {
    font-size: 18px;
    font-weight: 500;
    line-height: 24px;
    color: #212329;
    height: fit-content;
    cursor: pointer;
    text-decoration: underline;
    text-decoration-color: transparent;
    transition: .3s;
}

.link:hover {
  text-decoration-color: #212329;
}

2022-05-20 22:23 UTC, Miteugene commented on blocks/link/link.css
> +    transition: .5s ease-out;
Все остальное мне нравится) Код легко читать, все понятно.

2022-05-21 01:01 UTC, GlebKirsan requested changes
Пока только пробежался по самому коду, когда доберусь до локального запуска, может ещё идеи появятся

2022-05-21 04:59 UTC, Virshinia commented on blocks/link/link.css
> +    transition: .5s ease-out;
Поправила

2022-05-21 04:59 UTC, Virshinia commented on blocks/link/link.css
> +    line-height: 24px;
Поправила

2022-05-21 05:00 UTC, Virshinia commented on blocks/title/title.css
> +    line-height: 28px;
И тут поправила :)

2022-05-21 06:50 UTC, Miteugene approved these changes

2022-05-21 07:44 UTC, IliaGorin approved these changes

2022-05-21 15:30 UTC, GlebKirsan approved these changes

2022-05-21 15:30 UTC, merged